//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiqueShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int id_cart { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_item { get; set; }
        public int quantity { get; set; }
        public Nullable<System.DateTime> added_date { get; set; }
        public Nullable<bool> is_active { get; set; }
    
        public virtual Items Items { get; set; }
        public virtual Users Users { get; set; }
    }
}
