//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiqueShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favorites
    {
        public int id_favorite { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_item { get; set; }
    
        public virtual Items Items { get; set; }
        public virtual Users Users { get; set; }
    }
}
