//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiqueShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_logs
    {
        public int id_log { get; set; }
        public Nullable<int> id_item { get; set; }
        public string changed_field { get; set; }
        public string old_value { get; set; }
        public string new_value { get; set; }
        public Nullable<System.DateTime> change_date { get; set; }
    
        public virtual Items Items { get; set; }
    }
}
