//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiqueShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Items()
        {
            this.Cart = new HashSet<Cart>();
            this.Favorites = new HashSet<Favorites>();
            this.Item_logs = new HashSet<Item_logs>();
            this.Sales = new HashSet<Sales>();
        }
    
        public int id_item { get; set; }
        public string name_item { get; set; }
        public Nullable<int> year { get; set; }
        public string condition { get; set; }
        public string authenticity { get; set; }
        public Nullable<decimal> purchase_price { get; set; }
        public Nullable<decimal> selling_price { get; set; }
        public Nullable<System.DateTime> arrival_date { get; set; }
        public string image { get; set; }
        public Nullable<int> id_category { get; set; }
        public Nullable<int> id_material { get; set; }
        public Nullable<int> id_supplier { get; set; }
        public Nullable<int> id_status { get; set; }
        public Nullable<int> id_origin_country { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Cart { get; set; }
        public virtual Categories Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorites> Favorites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_logs> Item_logs { get; set; }
        public virtual Materials Materials { get; set; }
        public virtual Origin_countries Origin_countries { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales> Sales { get; set; }

        public string CurrentPhoto
        {
            get
            {
                if (String.IsNullOrEmpty(image) || String.IsNullOrWhiteSpace(image))
                {
                    return "/Images/picture.jpg";
                }
                else
                {
                    return "/Images/" + image;
                }
            }
        }


    }
}
