//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiqueShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int id_sale { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_item { get; set; }
        public Nullable<System.DateTime> sale_date { get; set; }
        public Nullable<decimal> final_price { get; set; }
    
        public virtual Items Items { get; set; }
        public virtual Users Users { get; set; }
    }
}
